### ISSUE TITLE
감사합니다. :)

### ISSUE THREAD

**Issue by suya55** [humit0/kakao_auto_reply#1]
안녕하세요. 카카오 자동응답 서비스 개발자입니다.
언제나 좋은 의견주시고 관심가져주셔서 감사합니다.

그리고 이런 훌륭한 툴까지 만들시다니 멋집니다.

더 발전해서 좋은 레퍼런스가 될 수 있길 기대합니다.

건승하십시오.

참. 지나가다가... 
1. ui가 너무 개발자스러우니 bootstrap이라도 적용해보심이 어떨까요?
2. 꼭 apache가 아니더라도 [php -S](http://php.net/manual/kr/features.commandline.webserver.php) 옵션으로도 서버를 띄울수 있으니 이부분도 언급해두면 초보 php 유저들에게는 도움이 될수도 있겠네요. :)

**Comment by humit0** [comment]
확실히 bootstrap이나 materialize를 적용하는 것을 고려해보아야 겠네요.
2번 항목의 경우에는 .htaccess의 mod_rewrite기능으로 구현을 해서 php -S 로는 안될 것 같네요 ^^

**Comment by arizona95** [comment]
안녕하세요. 카카오톡 봇을 만들면서 이 글을 참고했었는데요, 초보적인 것에서 막혀서 질문드려두 될까요?
알려주신대로 아파치서버에 auto_reply 를 깔고 실행시켰는데 lib.php 파일 50 번줄에서 
$allowed_ips = ["110.76.143.234", "110.76.143.235", "110.76.143.236"]; 이라고 되있는데 이렇게 써도 되나요? 파싱 오류가 나서요ㅠㅠ
또 array () 로 바꿔서 돌아가긴 했는데 그다음 install 페이지가 아예 작동을 안합니다. 무엇이문제인가요?
