### ISSUE TITLE
디자인 업데이트 후 문제점

### ISSUE THREAD

**Issue by ltm-lab** [humit0/kakao_auto_reply#11]
디자인이 깔끔해진 것은 매우 마음에 드네요 :)

하지만 업데이트 후 홈 키보드 보기 및 수정과 테스트 하기 기능이 동작하지 않습니다 :(

확인 부탁드립니다!

**Comment by humit0** [comment]
흠... 혹시 config.php 파일에서 BASE_URL을 제대로 설정하셨나요?

**Comment by ltm-lab** [comment]
네 mydomain.com 을 "http://mydomain.com/" 으로 작성해 두었습니다

**Comment by humit0** [comment]
.htaccess 파일도 맞게 서버 환경에 맞게 수정해주셨나요? 만약 제대로 작성해주셨다면 주소를 알려주시기 바랍니다.

**Comment by ltm-lab** [comment]
스킨을 업데이트 하기 전까진 정상적으로 작동했었습니다. 따로 건드린건 없구요.

+버튼 생성에 제출하기 버튼도 동작하지 않습니다.
+로그인 시 엔터키로 로그인은 동작하나 로그인 '버튼'을 눌렀을 땐 반응이 없네요

+추가
로그인 시 '로그인'텍스트를 클릭하면 동작하고 여백 클릭시 반응이 없는거였네요. 제출하기는 텍스트를 눌러도 동작안합니다.

**Comment by humit0** [comment]
MaterializeCSS가 input 태그의 경우에는 버튼 바깥쪽이 아니라 안에 텍스트를 클릭해야지 동작이 하게 되어있네요...

**Comment by humit0** [comment]
그리고 Admin 페이지에서 F12를 누르셔서 개발자 도구를 켜신 다음에 Network 부분에 가셔서 아래와 같이 요청 화면을 찍어서 올려주시기 바랍니다. 일단 제가 사용하는 환경에서는 잘 동작하는 걸로 나오네요..
![image](https://cloud.githubusercontent.com/assets/8676247/19829479/c24de534-9e1d-11e6-9f5a-0f73ec6eb434.png)

**Comment by jwt8280** [comment]
버튼 추가하기에서 하는 모든것들이 업로드가 안됩니다. 
저는 디자인이 바뀐상태에서 처음 접해보고 한거라서 어떤 문제인지 잘 모르겠습니다.
처음 아이디와 비번 등록 그리고 번튼 처음 추가하는 부분까지 모두 잘 됐습니다.
그리고 카카오톡봇안에 API자동응답을 통해서 URL 등록 후 버튼 추가하기 안에 텍스트를 넣고 "Default Keyboard를 사용합니다." 를 체크하고 제출하기를 눌렀더니

/resource/msg/msg_286d6212c9d385774521da8d77e1fa74.php�뿉 �꽦怨듭쟻�쑝濡� �벐�뿬議뚯뒿�땲�떎. �룎�븘媛�湲� 

위와 같은 이상한 문자가 뜹니다. 

저같은 경우는 APMSeTUP7을 통해 HTTP서버를 돌리고 있고 PHP version문제로 업로드하여 현재 5.4.14 버전을 사용하고 있습니다. php를 뿐만 아니라 APMSETUP 역시 처음 접해 보는거라
PHP버젼 문제인지 아니면 어떤문제인지 자세히 알고 싶어 여기에 글을 올리게 되었습니다.

**Comment by jwt8280** [comment]
안녕하세요. 올리신 글과 파일덕분에 무사히 카카오톡 봇 자동응답기능을 구현할 수 있었습니다. 감사합니다. 다른게 아니라 구현 도중 몇 가지 궁금한게 있어 여기에 글을 남깁니다.

제가 주신파일을 통해 구현한 내용은 자동응답기능을 통해 텍스트와 사진을 전송하는 것 까지였습니다.

1 첫번째 질문은  사진의 경우, 잘 전송되었지만  고객은 자동응답기능을 통해 받은 사진을 저장 혹은 사진 확대를 하지 못하게 되어있던데 사진저장 및 확대를 할 수 있는것이 가능한지 알고 싶습니다.

제가 옐로아이디 고객상담팀과 통화한 바로는 자동응답기능안에서는 이러한 부분이 불가하며, Excel 파일을 읽는 것과 저장 및 확대 기능이 불가능하다고 들었기 때문입니다. 

2. 두번쨰로는 미디어 영상이 URL을 통해 가능은 하지만 자동응답기능에선 불가하다는 답변을 들었는데 올리신글 중  "PROJECT 2.0 카카오톡 자동 응답봇 만들기[3]"에서 글을 인용한다면 "Default Keyboard를 체크 하지 않고 그 아래 텍스트 상자도 비어 있을 경우 미디어 업로드(사진, 동영상,음성)를 할 수 있게 되어 있습니다. " 라고 되어 있어서 혹시나 미디어업로드를 구현하셨는지 알고 싶어 글을 남기게 되었습니다. 미디어 업로드가 되었다면 자세하게 방법 좀 부탁드리겠습니다. PHP와 웹서버 모두 처음 해보는거라서 생각보다 시간이 많이 걸렸습니다. 그래도 주신 파일과 올리신 글때문에 많이 도움이 되었기에 감사하게 생각하며, 도움을 받고자 글을 올리게 되었습니다.


==================================================================
간단하게 요약하자면
1. 사용자 입장에서 자동응답기능 키보드를 통해 사진을 받았는데 이것을 저장 및 확대 할 수 있는 기능이 있는지 궁금합니다.

2. 주신 파일을 통해 사진, 동영상, 음성 기능 즉 미디어 업로드가  가능하다고 하셨는데 이러한 기능을 구현하는 방법을 알고 싶습니다. 자세하게 하신부분을 캡쳐해서 설명해주신다면 감사하겠습니다.
