### ISSUE TITLE
미디어 영상 및 사진 저장기능에 대한 궁금점

### ISSUE THREAD

**Issue by jwt8280** [humit0/kakao_auto_reply#12]
안녕하세요. 올리신 글과 파일덕분에 무사히 카카오톡 봇 자동응답기능을 구현할 수 있었습니다. 감사합니다. 다른게 아니라 구현 도중 몇 가지 궁금한게 있어 여기에 글을 남깁니다.

주신파일을 통해 제가 구현한 내용은 자동응답기능을 통해 텍스트와 사진을 전송하는 것 까지였습니다.

첫번째 질문은 사진의 경우, 잘 전송되었지만 고객은 자동응답기능을 통해 받은 사진을 저장 혹은 사진 확대를 하지 못하게 되어있던데 사진저장 및 확대를 할 수 있는것이 가능한지 알고 싶습니다.

제가 옐로아이디 고객상담팀과 통화한 바로는 자동응답기능안에서는 이러한 부분이 불가하며, Excel 파일을 읽는 것과 저장 및 확대 기능이 불가능하다고 들었기 때문입니다. 

두번쨰로는 미디어 영상이 URL을 통해 가능은 하지만 자동응답기능에선 불가하다는 답변을 들었는데 올리신글 중 "PROJECT 2.0 카카오톡 자동 응답봇 만들기[3]"에서 글을 인용한다면 "Default Keyboard를 체크 하지 않고 그 아래 텍스트 상자도 비어 있을 경우 미디어 업로드(사진, 동영상,음성)를 할 수 있게 되어 있습니다. " 라고 되어 있어서 혹시나 미디어업로드를 구현하셨는지 알고 싶어 글을 남기게 되었습니다. 미디어 업로드가 되었다면 자세하게 방법 좀 부탁드리겠습니다. PHP와 웹서버 모두 처음 해보는거라서 생각보다 시간이 많이 걸렸습니다. 그래도 주신 파일과 올리신 글때문에 많이 도움이 되었기에 감사하게 생각하며, 도움을 받고자 글을 올리게 되었습니다.

간단하게 요약하자면
1. 사용자 입장에서 자동응답기능 키보드를 통해 사진을 받았는데 이것을 저장 및 확대 할 수 있는 기능이 있는지 궁금합니다.
2. 주신 파일을 통해 사진, 동영상, 음성 기능 즉 미디어 업로드가 가능하다고 하셨는데 이러한 기능을 구현하는 방법을 알고 싶습니다. 자세하게 하신부분을 캡쳐해서 설명해주신다면 감사하겠습니다.

**Comment by humit0** [comment]
1. 고객상담 팀에서 안된다고 하는 기능은 당연히 구현이 불가능합니다. 비슷하게 구현하는 방법은 메시지 내용에 이미지 링크를 같이 첨부를 해서 링크를 클릭하면 확대 축소가 가능하다는 점을 이용할 수 있습니다.
2. 미디어업로드의 경우 https://github.com/humit0/kakao_auto_reply#36-libaddphp 항목을 참조하여 구현을 하시면 됩니다. 참고로 미디어 업로드의 경우에는 자신의 서버에 업로드가 되는 것이 아니라 카카오톡 서버에 업로드가 되어서 그 미디어에 대한 링크가 응답으로 옵니다. ( https://github.com/plusfriend/auto_reply#52-메시지-수신-및-자동응답-api 를 참조하시기 바랍니다.)
