### ISSUE TITLE
버튼을 추가해도

### ISSUE THREAD

**Issue by disasterpiec** [humit0/kakao_auto_reply#13]
http://disasterpiec.esy.es/kakao/

버튼을 추가 해도
fail to load homekeyboard가 뜨네요 ㅠㅠ

keyboard.config에도 계속 빈파일로 남아있고요.

config랑 htaccess 도 맞게 확인 하였습니다.

어떻게 해야하나요 ㅠㅠ

프로그램만드시느라 힘드셨을텐데

감사합니다.

**Comment by humit0** [comment]
.htaccess 파일을 어떻게 작성하셨는지 올려주시기 바랍니다.
keyboard.config.php 파일이 빈파일로 있는 것은 kakao 폴더의 권한 문제로 보이네요.

**Comment by disasterpiec** [comment]
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.*)$ /kakao/index.php/?id=$1 [L]
</IfModule>

이렇게 수정했어요!

그리고 파일권한은 777로 했는데도 똑같네요 ㅜㅜ

**Comment by disasterpiec** [comment]
아됐네요 kakao 폴더를 없애버리고 했더니 됐습니다. 

권한 올려도 안됐었어요

감사합니다.

**Comment by disasterpiec** [comment]
그리고 우분투 서버는 안되네요 ㅋㅋㅋㅋ

**Comment by humit0** [comment]
우분투 서버에서도 잘 동작합니다. 서버설정을 제대로 하지 않은 것으로 보입니다.

**Comment by humit0** [comment]
우분투 서버에서도 잘 동작합니다. 서버설정을 제대로 하지 않은 것으로 보입니다.
