### ISSUE TITLE
자동응답 API 관련 문의 드립니다.

### ISSUE THREAD

**Issue by jungjmw** [humit0/kakao_auto_reply#14]
안녕하세요~
좋은 툴을 만들어 주시고 활용하게 해 주셔서 감사드립니다.

현재 카페24측과 호스팅어 측에 호스팅을 진행하고 있습니다.

자동응답 API를 설치하기 위해서 두 군데에 만들어주신 툴을 설치하고 진행했습니다.

1. 카페24에 설치한 파일에서는 우선 설치도 되지 않고 

Parse error: syntax error, unexpected '[' in /home/hosting_users/goodmanguide1/www/auto_reply/lib.php on line 50

라고 떴습니다. 
우선 ip제한이 되어 있는 것 같아서 ip제한을 풀었지만 계속해서 같은 메시지가 나왔습니다.

2. 호스팅어에 넣은 툴은 블로그를 보고 따라하니 설치 진행까지 깔끔하게 되었지만,  API테스트에서 벽에 부딪혔습니다.
네가지 테스트 중에 세가지는 다 'OK 200"가 떴습니다만,
Fail 415 : wrong keyboard initialization 가 떴어요.

우선 혹시 몰라서 IP 허용은 해 놓았지만, 해결 방법을 잘 모르겠습니다..

염치 불구하고 도움 부탁드립니다.

감사합니다

**Comment by humit0** [comment]
cafe24의 경우에는 php 버전이 5.3 이상이 아닌 것으로 보이네요.
그리고 호스팅어의 경우에는 아마 .htaccess 설정이 제대로 되지 않는 것으로 보입니다.

**Comment by jungjmw** [comment]
답변 감사합니다.
그러면 지금 호스팅 가능한 서버 두군데 다 api 사용이 불가능 한 것이군요
그럼 다른 호스팅 서버를 찾아서 운영을 하는 방법을 택했습니다.
닷홈에서 호스팅을 하게 되니 가능하군요!
답변 감사드립니다.

추가로 현재는 버튼식으로만 가능한 것 같던데, 혹시 텍스트 형식으로 입력을 받아서 답변을 주려고 하면 어디서 무엇을 수정해야 할까요?

**Comment by humit0** [comment]
그 기능은 직접 구현하셔야 하는 사항으로 router.php 파일을 수정하시면 됩니다.
