### ISSUE TITLE
키보드 이니셜 오류

### ISSUE THREAD

**Issue by disasterpiec** [humit0/kakao_auto_reply#15]
안녕하세요!

disasterpiec.ivyro.net 에서하려고 하는데 계속 키보드 입력이 안되네요 ㅠㅠ

어떻게 하면 될까여 ㅜㅜ

**Comment by disasterpiec** [comment]
mod_rewrite도 설치되어있고 안될이유가 없는데 ㅠㅠ

**Comment by humit0** [comment]
mod_rewrite 모듈이 설치되어 있더라도 호스팅 서버 측에서 설정을 추가해주어야 합니다.
한 번 호스팅 업체에 문의해보시기 바랍니다.
