### ISSUE TITLE
버튼 추가하기가 안됩니다..

### ISSUE THREAD

**Issue by auvergne394** [humit0/kakao_auto_reply#18]
입력을 다 하고 제출을 하면
"~~에 성공적으로 쓰여졌습니다"
이 화면이 떠야 정상인 것 같은데, 저는 그냥 공백이네요.. 아무것도 안뜹니다 ㅠㅠ
권한은 아주 극단적으로 777로 모두 부여를 했고, mod_rewrite까지 정상적으로 설치된 것 같은데(Home keyboard는 정상적으로 추가됩니다)
뭐가 문제인지 모르겠네요...
제가 수동으로 resource/msg/ 폴더에 md5함수를 써가면서 파일명을 만들어서 올바른 메세지파일을 만들고 나면 제대로 작동을 하긴 하는데, 그렇게 되면 사용자의 입력 타입을 buttons로 밖에 못해서... 제가 원하는 건 사용자의 text타입에 대한 자동 응답 API거든요..ㅠㅠ

**Comment by humit0** [comment]
입력후 제출을 하면 나오는 화면을 캡쳐해서(주소 창 포함) 올려주시기 바랍니다.

**Comment by auvergne394** [comment]
다른거 시도해본다고 다 갈아엎고 오늘 다시 해봤는데 이젠 빈 창이 아니라 에러메세지가 뜨네요..
![_2016_11_28_11_29_18_27](https://cloud.githubusercontent.com/assets/24209664/20654674/cd2b3fee-b55e-11e6-8303-e9dbc2ce932c.png)
▲이렇게 해서 제출을 하면
![_2016_11_28_11_29_24_342](https://cloud.githubusercontent.com/assets/24209664/20654683/d78dca56-b55e-11e6-9903-fdfb0ad9d6af.png)
▲이렇게 뜹니다.
![_2016_11_28_11_28_57_34](https://cloud.githubusercontent.com/assets/24209664/20654689/e22d01b6-b55e-11e6-92d2-8ec3b994bdd4.png)
▲홈키보드는 정상적으로 추가되는 상황이고
![_2016_11_28_11_27_08_786](https://cloud.githubusercontent.com/assets/24209664/20654691/e96899b8-b55e-11e6-8691-1cbad55fb6ff.png)
▲phpinfo 문서
![_2016_11_28_11_31_05_716](https://cloud.githubusercontent.com/assets/24209664/20654700/f64ac764-b55e-11e6-8b17-d54d5caf2b0f.png)
![_2016_11_28_11_31_09_765](https://cloud.githubusercontent.com/assets/24209664/20654703/f64e2d28-b55e-11e6-820e-310c922aa240.png)
![_2016_11_28_11_31_15_233](https://cloud.githubusercontent.com/assets/24209664/20654702/f64ddd5a-b55e-11e6-8857-95c741cd57c9.png)
![_2016_11_28_11_31_26_664](https://cloud.githubusercontent.com/assets/24209664/20654701/f64d3fee-b55e-11e6-9397-e7e827eee943.png)
▲apache2.conf내 rewrite설정입니다.

![_2016_11_28_11_26_50_339](https://cloud.githubusercontent.com/assets/24209664/20654725/3751175e-b55f-11e6-8400-aea0219bfc9d.png)
▲ 모든 문서들은 권한을 777로 해놨구요..


※참고로 서버 호스팅은 digitalocean에서 구매를 해서 LAMP를 설치한 상태입니다.

**Comment by humit0** [comment]
현재 페이지가 500 에러라 제가 직접 확인을 할 수가 없네요..
config.php 파일에서 DEBUG를 TRUE 값으로 바꾸어주시고 에러 로그를 기록할 수 있도록 한 다음에 버튼 추가를 누르셔서 나오는 에러 로그를 첨부해주시기 바랍니다.

**Comment by auvergne394** [comment]
![_2016_11_28_13_52_50_372](https://cloud.githubusercontent.com/assets/24209664/20656612/0c8f767e-b572-11e6-8f4b-1b7889476c90.png)
이렇게 뜨네요

.
.
.
그리고 일반 화면에서도 이런 Notice가 뜨는데 정상인가요?
![_2016_11_28_13_53_56_47](https://cloud.githubusercontent.com/assets/24209664/20656623/2f6d792a-b572-11e6-83a1-f6fe2bc47e40.png)

**Comment by humit0** [comment]
http://stackoverflow.com/questions/35756821/call-to-undefined-function-mb-strlen-on-php-7-ubuntu-14-04/35756822
php7에서는 mb_strlen 함수를 바로 사용할 수 없는 것 같네요. 위 링크의 글을 참고해서 진행해보시기 바랍니다.

그리고 Notice의 경우에는 크게 문제가 되지 않습니다. 다만 실제로 서비스를 할 때는 DEBUG를 FALSE로 바꿔주시기 바랍니다.
나중에 업데이트를 할 때 참고하도록 하겠습니다.

**Comment by auvergne394** [comment]
해결됐습니다!! 감사합니다!!

**Comment by ochooma** [comment]
저도 거의 같은 문제인데. 어떻게 해결하셨는지 
도와 주실 수 있으실까요?
부탁드립니다.

**Comment by ochooma** [comment]
저는 버튼 추가하기에서 제출하고 나서. 
Home Keyboard 보기에서는 undefine 으로 버튼이 나타나지 않습니다.
그렇치만 resource 에는 메시지 파일이 생성됩니다.
또한 keyboard_config.php 파일에서 메뉴얼로 메뉴를 작성하여 보지만, 
응답메시지의 해당 메시지는 자동으로 발송 되지 않습니다.
스크린샷 올립니다. 부디 도와 주시기 바랍니다.
![2016-12-18 5 47 51](https://cloud.githubusercontent.com/assets/578224/21292494/fabf3176-c54a-11e6-99f4-c49089cc5568.png)
![2016-12-18 5 48 02](https://cloud.githubusercontent.com/assets/578224/21292495/fabfd32e-c54a-11e6-90af-36c9e0c8ba8c.png)
![2016-12-18 5 48 16](https://cloud.githubusercontent.com/assets/578224/21292496/fac066a4-c54a-11e6-893e-470518644e98.png)
![2016-12-18 5 48 32](https://cloud.githubusercontent.com/assets/578224/21292497/facbbe96-c54a-11e6-97e9-73b23a47825d.png)
