### ISSUE TITLE
키보드 initialization 오류

### ISSUE THREAD

**Issue by terryeah** [humit0/kakao_auto_reply#2]
세팅 과정에서처럼 BASE_URL을 제 사이트 URL로 바꾸고 서버에 [http://julysfx.com/](http://julysfx.com/) php 5.6 가동 중이구요. apache도 mod_rewrite 모듈이 설치되어 있습니다. 

그리고 나머지 폴더와 파일들을 제 사이트에 옮겨놓고 옐로 아이디 관리자 페이지로 가셔서 URL에 [http://julysfx.com/](http://julysfx.com/) 라고 치고 API Test를 했더니 키보드부터 에러가 나오네요. 

`Required*`
`Initialize Api test : Fail 405 : wrong keyboard initialization`

**keyboard.config.php**에는 아무것도 없길래 아래와 같은 코드를 넣었습니다. 
`{
    "type" : "buttons",
    "buttons" : ["#옵션1", "#옵션2", "#옵션3", "#옵션4", "#옵션5", "#옵션6", "#옵션7", "#옵션8", "#옵션9", "#옵션10", "#옵션11", "#옵션12"]
}`

어떻게 하면 좋을까요?

**Comment by humit0** [comment]
http://humit.tistory.com/250
이 블로그에 처음 세팅하는 방법에 대해서 나와 있으니 여기대로 해보시기 바랍니다.
그리고 링크에서 테스트를 해보니 apache의 mod_rewrite 모듈이 적용이 되지 않았습니다.
따로 호스팅을 받고 계시는 건가요 아니면 집에서 세팅을 하신건가요?

**Comment by terryeah** [comment]
[zuver.net.au](http://zuver.net.au)에서 호스팅 받고 있습니다. 
질문 하기 전에 직접 문의를 해봤는데 제 서버에 apache mod_rewrite 모듈이 설치되어 있다고 했었거든요.

지금 막 블로그 보고 따라 해봤는데 관리자페이지에 로그인까지 다 되어있는 상태에서 마지막에 옐로페이지에서 API Test할 때 또 아래처럼 에러가 나네요. 

`Required*`
`Initialize Api test : Fail 405 : wrong keyboard initialization` 

그리고 관리자페이지 로그인까지 가는 과정에서도 URL에 계속 BASE_URL이 붙어있길래 편법으로 일일이 URL에서 BASE_URL을 지우고 PHP 파일을 열어서 진행했습니다.

**Comment by humit0** [comment]
config.php 파일을 열어서 define("BASE_URL", "");를 define("BASE_URL", "http://julysfx.com/"); 로 수정하신 것이 맞나요?
그리고 호스팅 회사에서 mod_rewrite가 제대로 동작하지 않는다고 문의를 하셔봐야 할 것 같습니다. 원래는 http://julysfx.com/keyboard 를 입력하면 htaccess파일에서 http://julysfx.com/index.php?id=keyboard 로 이동시켜주는 형태인데 지금 그렇게 동작을 하고 있지 않는 것 같습니다.

**Comment by terryeah** [comment]
죄송합니다. 제가 잘못 이해하고 `define("BASE_URL", "http://julysfx.com/");` 이렇게 넣어야 할 부분을 `define("http://julysfx.com/", "");` 이렇게 두고 있었네요.

하지만 아직도 키보드 부분이 해결되지 않아서 호스팅 회사에 제대로 동작하지 않는다고 문의하였습니다. 
어떻게 되었는지 업데이트 해드리겠습니다.

여쭤보고 싶은 점이 2가지가 있는데요:
1. 제 서버 public_html 폴더에 .htaccess 파일이 보이지 않아 제가 잘못 올렸나 싶어서 .htaccess란 이름의 파일을 만들려고 하니까 이미 존재하는 파일 이름과 같다고 하면서 새 파일이 안 만들어졌거든요. 원래 서버엔 파일 이름에 . 으로 시작하는 파일들은 저절로 안 보이게 되나요 아니면 호스팅 회사마다 다른가요? .gitignore 파일도 보이지 않습니다. 
2. public_html 폴더에 keyboard란 이름의 파일에 파일 확장자를 붙이지 않고 아래와 같은 코드를 입력해서 넣으면 API Test가 통과되거든요. 첨부하신 PHP 파일들만 넣을 땐 안 되다가 keyboard란 이름의 파일만 넣으면 API Test가 통과되는 게 혹시 감이 잡히시는 게 있으신가요? 아니면 이게 바로 Apache의 mod_rewrite 모듈이 정상적으로 작동이 안 해서 그런 건가요?

`{
    "type" : "buttons",
    "buttons" : ["#옵션 1", "#옵션 2", "#옵션 3"]
}`

계속되는 빠른 답변 감사드립니다.

**Comment by terryeah** [comment]
업데이트: 방금 호스팅 회사에서 답장이 왔습니다. Apache mod_rewrite 모듈 다시 설치하고 활성화했다고 하네요. 컴파일한 파일 이름까지 저한테 알려주네요. 
하지만 여전히 키보드 부분은 해결이 되지 않았습니다.

**Comment by humit0** [comment]
흠... htaccess 파일의 설정을 보여주시기 바랍니다.

**Comment by terryeah** [comment]
htaccess 파일이 업로드는 되어있었으나 안에 내용이 없어 채워넣었더니 잘 작동합니다. 
감사합니다.
