### ISSUE TITLE
입력방식 text

### ISSUE THREAD

**Issue by auvergne394** [humit0/kakao_auto_reply#20]
버튼 추가하기 부분에서 'Default Keyboard를 사용합니다'를 클릭하지 않고, 아래 텍스트 박스에 아무런 값도 입력을 하지 않으면 키보드로 입력을 받을 수 있습니다.
그리고 키보드로 버튼 이름을 입력하고 전송을 누르면 해당하는 버튼이 실행됩니다.
즉 여기에선 '주사위'라는 입력을 하면 "주사위 눈의 수는 3입니다." 라는 응답을 볼 수 있는거죠.
-----------------------------------------------------------------------------------------------------------
블로그에 댓글에 적으신 내용을 바탕으로 해봤습니다.

![_2016_11_28_14_25_53_338](https://cloud.githubusercontent.com/assets/24209664/20657121/cf51dc16-b576-11e6-89b2-b22633890312.png)

그런데 이렇게 하고 나니 키보드 영역에 공란 버튼만 뜨더군요.
![kakaotalk_20161128_142638544](https://cloud.githubusercontent.com/assets/24209664/20657180/371c3e4a-b577-11e6-8b60-d2a20516b036.jpg)

그래서 keyboard파일을 따로 생성 했습니다.
{"type":"text"}

그러고나니 정상적으로 키보드영역이 나왔습니다.
![kakaotalk_20161128_142637940](https://cloud.githubusercontent.com/assets/24209664/20657145/ffd7172a-b576-11e6-929a-0f7cfd9c3508.jpg)
![kakaotalk_20161128_142637394](https://cloud.githubusercontent.com/assets/24209664/20657146/01000724-b577-11e6-81d0-3993b3c25286.jpg)
![kakaotalk_20161128_142636827](https://cloud.githubusercontent.com/assets/24209664/20657147/0205cfdc-b577-11e6-85d3-2c8179d387aa.jpg)

그런데 이후, 등록되지 않은 임의의 키워드를 전송하면
![kakaotalk_20161128_142636227](https://cloud.githubusercontent.com/assets/24209664/20657155/0ed85450-b577-11e6-906c-0185d4d10489.jpg)

위 그림과 같이 공란버튼이 다시 뜨네요.

**Comment by humit0** [comment]
https://github.com/humit0/kakao_auto_reply#36-libaddphp
여기서 7번 항목을 참조하시기 바랍니다.

**Comment by auvergne394** [comment]
제가 잘 몰라서 그러는지 어느부분이 문제해결을 할 수 있는 열쇠인지 모르겠네요..ㅠㅠ
정의되지 않은 메세지에 대한 응답 메세지는 떠도 상관이 없는데 키보드가 사라지고 버튼이 다시 뜨는게 문제입니다... 해당 항목으로 해결할 수 있는 부분인가요?

**Comment by auvergne394** [comment]
아 해결된 것 같습니다.! 아예 내용을 싹다 비워버리니 어느정도 해결이 되는 것 같네요
