### ISSUE TITLE
auto_reply 설치 문의

### ISSUE THREAD

**Issue by bncsoft** [humit0/kakao_auto_reply#21]
안녕하세요. 먼저 이렇게 좋은 툴을 공유해주셔서 감사드립니다.

현재 저는 AWS EC2 호스팅에 Apache2, PHP 5.5.9를 사용하고 있습니다. [http://www.bncsoft.com/phpinfo.php](http://www.bncsoft.com/phpinfo.php)

가이드해주신대로 config.php에 BASE_URL을 "[http://www.bncsoft.com/auto_reply](http://www.bncsoft.com/auto_reply)" 로 설정했구요.
.htaccess에도 서브디렉토리라 "/auto_reply/index.php/?id=$1 [L]"로 제대로 설정했습니다.

하지만 최초 설치시 입력되는 관리자 정보 및 키보드 값이 저장이 되지 않고 설치를 반복하는 현상이 있습니다.  (admin.config.php, keyboard.config.php 의 사이즈 0)

많이 바쁘시겠지만 해결방법 부탁드립니다.
감사합니다.

**Comment by humit0** [comment]
세팅과정 2번을 보시면 "참고로 입력할 URL은 /로 끝이 끝나야 합니다."라고 써놓았습니다. Readme 파일을 제대로 읽어주시면 감사하겠습니다..
https://github.com/humit0/kakao_auto_reply#2-세팅-과정

**Comment by bncsoft** [comment]
네 당연히 그부분은 설명대로 설정하였습니다.

<?php
 $ADMIN_INFO = NULL;
 $DEFAULT_KEYBOARD = NULL;
 // Update your base url.
 define("BASE_URL", "http://www.bncsoft.com/auto_reply/");
 // Only access kakao server or not.
 define("IP_CHECK", TRUE);
 // Show all warnings or not.
 define("DEBUG", FALSE);

 include_once __DIR__ . '/keyboard.config.php';
 include_once __DIR__ . '/admin.config.php';
 ?>

**Comment by bncsoft** [comment]
네 BASE_URL은 '/' 로 제대로 설정되어 있습니다.

최초 설치시 관리자 정보 입력 후 "계정 생성 완료"라고 나오고, 초기테스트도 완료되었다고 나오는데요.
설정확인 창에는 입력한 키보드 값이 아무것도 안나오면서
설정 확인하기

User : bncsoft

Default Keyboard : []

완료 <http://www.bncsoft.com/auto_reply/login.php>

완료를 누르면 다시 설치 화면으로 돌아가고 있습니다.

도와주시면 감사하겠습니다.




2016-11-30 23:41 GMT+09:00 humit <notifications@github.com>:

**Comment by humit0** [comment]
admin.config.php, keyboard.config.php 파일에 쓰기 권한이 없어서 0byte로 표시되는 것으로 보입니다. 두 개의 파일에 대해서 쓰기 권한을 주시고, resource 폴더와 해당하는 서브 폴더 모두 파일 권한을 777로 바꿔주시기 바랍니다.
