### ISSUE TITLE
초보개발자 질문드립니다!!

### ISSUE THREAD

**Issue by arizona95** [humit0/kakao_auto_reply#23]
안녕하세요. 카카오톡 봇을 만들면서 이 글을 참고했었는데요, 초보적인 것에서 막혀서 질문드려두 될까요?
알려주신대로 아파치서버에 auto_reply 를 깔고 실행시켰는데 lib.php 파일 50 번줄에서
$allowed_ips = ["110.76.143.234", "110.76.143.235", "110.76.143.236"]; 이라고 되있는데 이렇게 써도 되나요? 파싱 오류가 나서요ㅠㅠ
또 array () 로 바꿔서 돌아가긴 했는데 그다음 install 페이지가 아예 작동을 안합니다. 무엇이문제인가요?

**Comment by humit0** [comment]
php 버전이 5.3 이하인 것 같네요. 일단 array로 바꾸셔도 크게 문제는 되지 않습니다.
config.php 파일에서 DEBUG부분을 TRUE로 바꿔서 어떤 에러가 발생하는지 알려주시기 바랍니다.

**Comment by arizona95** [comment]
아아.. 감사합니다 php 버전 문제였습니다.
 php 5.4 이상에서만 동작하는 session_status()  함수가 작동하지 않은게 원인이였습니다.
5.3 이상이라 해서 php 5.3.27 으로 돌리고있어서 에러가 났었습니다!

**Comment by humit0** [comment]
아 그부분이 문제가 있었군요. 나중에 업데이트할 때 변경해야겠네요
