### ISSUE TITLE
잘 설치 되었습니다만, 꼭 좀 봐주세요.

### ISSUE THREAD

**Issue by ochooma** [humit0/kakao_auto_reply#26]
저는 버튼 추가하기에서 제출하고 나서.
Home Keyboard 보기에서는 undefine 으로 버튼이 나타나지 않습니다.
그렇치만 resource 에는 메시지 파일이 생성됩니다.
또한 keyboard_config.php 파일에서 메뉴얼로 메뉴를 작성하면,
버튼이 보이지만,
![2016-12-18 5 47 51](https://cloud.githubusercontent.com/assets/578224/21293192/5a5087e2-c560-11e6-8b3f-fab602156b16.png)
![2016-12-18 5 48 02](https://cloud.githubusercontent.com/assets/578224/21293191/5a4ec718-c560-11e6-8c7e-0907726917fd.png)
![2016-12-18 5 48 16](https://cloud.githubusercontent.com/assets/578224/21293193/5a5315de-c560-11e6-9b6a-33a8f970d659.png)
![2016-12-18 5 48 32](https://cloud.githubusercontent.com/assets/578224/21293194/5a5ea2a0-c560-11e6-8583-c9af451e59a9.png)

응답메시지의 해당 메시지는 자동으로 발송 되지 않습니다.
스크린샷 올립니다. 부디 도와 주시기 바랍니다.

**Comment by humit0** [comment]
저 부분이 undefined로 나오는 것을 보면 .htaccess의 문제가 클 수 있다고 생각합니다.
nginx가 아닌 apache로 웹서버를 운영하고 계시는 것이 맞으신가요?
