### ISSUE TITLE
안녕하세요 

### ISSUE THREAD

**Issue by ghost** [humit0/kakao_auto_reply#28]
Required*
Initialize Api test : Fail 415 : wrong keyboard initialization
Optional
Friend add Api test : OK 200
Friend block Api test : OK 200
Chatroom leave Api test : OK 200

"Initialize Api test : Fail 415 : wrong keyboard initialization" 
부분은 어떻게 해결하면 좋을까요 정말로 어떻게 할지 모르겠어요

**Comment by JonghyeokPark** [comment]
httpd.conf파일에서 Allowoveride를 모두 All로 바꿔서 해보세요!

**Comment by humit0** [comment]
config.php에서 IP_CHECK 부분에 있는 TRUE를 FALSE로 변경을 해주시고 해당하는 url을 알려주셔야 해결이 가능할 것 같습니다!
