### ISSUE TITLE
멀티플 키워드

### ISSUE THREAD

**Issue by terryeah** [humit0/kakao_auto_reply#3]
API형 자동응답 세팅을 모두 마친 후 잘 작동이 되고 있는데 어떻게 하면 여러개의 키워드에 자동응답을 하게끔 하는지 궁금하네요.

예를 들어서 '안녕'이라고 입력하면 "안녕하세요, 반갑습니다."가 나오는데, '안녕하세요'라고 쳐도 "안녕하세요, 반갑습니다."라고 반응하게끔 하고 싶습니다. 

resource/msg 폴더에 있는 '안녕' 키워드가 저장되어 있는 PHP 파일에서 `// content : 안녕` 부분에 추가를 하면 될 것 같은데 어떻게 하면 좋을지 알려주시면 감사하겠습니다.

**Comment by humit0** [comment]
다중 키워드 기능을 따로 제공해주고 있진 않습니다.
주석의 경우에는 단순히 그 파일이 어떤 키워드에 대한 응답인지를 쉽게 볼 수 있기 위해서 사용한 것입니다.

비슷하게 제작하시려면 '안녕'이라는 버튼을 추가한 것 처럼 '안녕하세요'라는 버튼을 추가하시면 됩니다.
