### ISSUE TITLE
버튼 추가 오류 문의

### ISSUE THREAD

**Issue by meiroo2** [humit0/kakao_auto_reply#30]
로그인 후에 버튼 추가를 하면 정상적으로 기록했다고 알림이 뜬 후 돌아가서 홈 키보드 보기/설정에
들어가보면 여전히 undefined라고 뜨네요. 리소스-msg 폴더 안을 확인해보면 파일은 정상적으로
기록되는 것 같습니다. 파일을 열어봐도 정상적으로 기록되있으나 홈 키보드/보기 설정에는 뜨지 않고
카톡에서도 작동 가능하지 않습니다. 해결 방법 부탁드립니다.
도움이 될까 싶어 관련 파일들의 내용을 올려드리겠습니다.

.htaccess 파일
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.*)$ /index.php/?id=$1 [L]
</IfModule>

config.php 파일
<?php
$ADMIN_INFO = NULL;
$DEFAULT_KEYBOARD = NULL;
// Update your base url.
define("BASE_URL", "http://meiroo3.ddns.net/");
// Only access kakao server or not.
define("IP_CHECK", TRUE);
// Show all warnings or not.
define("DEBUG", FALSE);

include_once __DIR__ . '/keyboard.config.php';
include_once __DIR__ . '/admin.config.php';
?>

**Comment by meiroo2** [comment]
확인해보니 keyborad_config에 제가 추가한 버튼이 없고 msg 폴더 안에만 php 파일로만 존재하네요.
윈도우에서 아파치와 php5.6을 연동해서 사용중입니다.

**Comment by humit0** [comment]
아마 keyboard_cofing.php 파일에 파일쓰기 권한이 없어서 그런 것 같네요. 해당 권한을 주시거나 아니면 
`<?php
$DEFAULT_KEYBOARD = array("안녕","주사위");
`

와 같이 배열에 인자를 넣어주는 방식으로 사용하시면 될 것 같습니다.
