### ISSUE TITLE
버튼 추가하기

### ISSUE THREAD

**Issue by SoreCarnival525** [humit0/kakao_auto_reply#33]
버튼추가하기에서 버튼 이름을 하고, 표시할 메시지까지 입력 후, Defualt Keyboard 체크하고 제출을 누르니, http://(ip)/auto_reply/admin.php?action=add&post=1로 이동되며 페이지를 표시할 수 없답니다..
어떻게 해야할까요?

**Comment by walter-ghost** [comment]
keyboard가 없어서 그런거같아요 failed to load home keyboard alert는 안뜨시나요?

**Comment by humit0** [comment]
해당 주소를 알려주셔야 정확히 어떤 부분에서 문제가 되는지를 알 수 있을 것 같습니다.
