### ISSUE TITLE
Failed to load Home keyboard

### ISSUE THREAD

**Issue by namsun** [humit0/kakao_auto_reply#35]
관리자에서 
Home Keyboard 보기 / 수정 을 누르면
위의 에러가 나오는데 라는 에러는 왜 뜨는걸까요??

keyboard 라는 폴더를 찾는거 같은데 존재하지 않아요.
어찌 해야 할지 좀 도와주세요.

Required*
keyboard Fail 415
wrong keyboard initialization

**Comment by walter-ghost** [comment]
httpd.conf 파일에서 #LoadModule rewrite_module modules/mod_rewrite.so 줄 찾아서 # 을 제거해주시고, <Directory "c:/Apache24/htdocs"> 줄 찾아서 아래 AllowOverride None을 AllowOverride All로 바꾸시면 될거에요

**Comment by namsun** [comment]
이제야 답변 보네요.
먼저 답변 감사합니다.
답변 보기전 처리는 되었지만..  walter-ghost님이 말씀해주신거와 같은 문제 였습니다.

#LoadModule rewrite_module modules/mod_rewrite.so 모듈만 열어두고

권한을 열어 주지 않았더군요..

감사합니다.
