### ISSUE TITLE
Home Keyboard 보기/수정 에러

### ISSUE THREAD

**Issue by naegeon** [humit0/kakao_auto_reply#39]
안녕하세요
이렇게 멋진 솔루션을 제공해주셔서 대단히 감사드립니다.

개발자님께서 추천해주신 방법으로
전 과정을 설정하고, 카카오에서도 적용완료하였구요

다만, 최초 Keyboard 설정에서 3개를 임의로 설정하고
저장을 했으나 저장이 안된것으로 나와 테스트가 안되는 상황이라서요

Home Keyboard 를 수동으로 editor 이용해 수정하는 방법이 있을가해서 문의드립니다.
감사합니다.

![screenshot 2017-12-02 at 14 40 46](https://user-images.githubusercontent.com/28140145/33512226-e4b24576-d76e-11e7-85f7-c9e8cfd55664.png)
![screenshot 2017-12-02 at 14 41 01](https://user-images.githubusercontent.com/28140145/33512227-e4dfeefe-d76e-11e7-90bf-b29b011d687d.png)

**Comment by humit0** [comment]
keyboard.config.php 에 쓰기 권한이 있는지 확인해보시고 쓰기 권한이 없으면 권한을 추가해주시면 됩니다.
