### ISSUE TITLE
홈 키보드

### ISSUE THREAD

**Issue by terryeah** [humit0/kakao_auto_reply#4]
제가 어떤 걸 건드렸는지 모르겠는데 다른 건 다 잘 작동하는데 홈 키보드가 뜨지 않네요. 어디서 설정 변경이 가능한가요?

**Comment by humit0** [comment]
홈 키보드에 대한 설정은 keyboard.config.php 파일에 아래 사진처럼 배열 형태로 저장이 됩니다.
![02](https://cloud.githubusercontent.com/assets/8676247/17240640/9d0350ac-55a7-11e6-958a-3bf57aa47cb4.jpg)
일단 이 파일을 여셔서 비어있는지 확인해보시기 바랍니다.
