### ISSUE TITLE
Home Keyboard 설정

### ISSUE THREAD

**Issue by raonorion** [humit0/kakao_auto_reply#40]
![123](https://user-images.githubusercontent.com/34261951/33591278-0e365eea-d9c8-11e7-849f-63a29c38fc9a.JPG)

안녕하세요. 덕분에 챗봇은 공부하고 있는 학생입니다.
설명대로 셋팅중에 
home keyboard 설정이 정의되지 않은 걸로 나와서
더 이상의 진행이 안되네요.
쓰기 권한은 모두 확인했습니다.

**Comment by humit0** [comment]
일단 keyboard.config.php에 값이 잘 들어가있는지 확인하시기 바랍니다.
제대로 들어가 있다면, .htaccess 문제이거나 아니면 웹방화벽 문제입니다.
