### ISSUE TITLE
복수의 키워드를 인식시키고 싶습니다.

### ISSUE THREAD

**Issue by Haokim** [humit0/kakao_auto_reply#41]
덕분에 아주 손쉽게 자동응답봇을 만들었습니다. 감사드립니다. ㅠㅠ
(코딩 1도 모르는 사람인데도 불구하고요...)

복수의 키워드를 인식시키고 싶은데 관련 파일을 도저히 찾을수가없네요.

예를들어서, "물리학" 이라는 글자와 "ㅁㄹㅎ" 이라는 글자를 모두 같은 것으로 인식해서 같은 내용이 나오게 하는 식으로 만들고자하는데, 어디를 손봐야할지 도저히 모르겠습니다.

그래서 웹상에서 버튼추가하기에 버튼이름을 "물리학||ㅁㄹㅎ"이라고 넣었는데 "물리학||ㅁㄹㅎ"이렇게 입력해야 인식하더라구요.

그래서 모든 파일을 sublime text3 로 열어서 봐도 "물리학"이라는 단어 자체를 못찾겠어요.
어떻게 해야할지 감이 안옵니다. ㅠㅠ

도와주시면 감사하겠습니다.

**Comment by humit0** [comment]
현재 구현된 방식은 키워드 하나당 파일을 하나씩 만들어서 거기에 대응을 하는 방식으로 구현이 되어있습니다.
복수의 키워드를 인식하는 방법은 현재 없으며 비슷한 방식으로 "물리학"이라는 키워드에 추가한 내용과 "ㅁㄹㅎ"이라는 키워드에 추가된 내용이 동일하게 만드는 방법밖에 없습니다.
그리고 관리자 페이지에 들어가셔서 '파일명 찾기' 메뉴에 가셔서 키워드를 입력하시면 해당하는 파일의 이름을 알 수 있습니다.
