### ISSUE TITLE
카카오 봇 DB연결문의

### ISSUE THREAD

**Issue by SongYH** [humit0/kakao_auto_reply#42]
안녕하세요 만들어주신 카카오봇 잘쓰고 있습니다.

다름이 아니라 메시지에서 db연결을 통해 답변을 뿌리고 싶은데

테스트 php 파일에서는 됐는데 메시지 php 파일에서는 db연결이 안되더라구요

혹시 방법이 따로 있나요?

<?php

// content : 카테고리안내
use \kakao\Msg;
use \kakao\Msg\Message;
use \kakao\Keyboard;

include("../../dbconnect.php");
//4. 쿼리 생성
$query = "select seq, category from kakao_category";

//5. 쿼리 실행
$result = mysqli_query($conn, $query);
$category_list = "";
//6. 결과 처리
while($row = mysqli_fetch_array($result)) {
	$category_list = $category_list.$row['category'];
}

echo new Msg(
	new Message(
		"$category_list",
		NULL,
		NULL
	),
	TRUE
);

//6. 연결 종료
mysqli_close($conn);

**Comment by humit0** [comment]
어떤 식으로 소스코드를 짜셨는지를 알려주셔야 합니다.
