### ISSUE TITLE
415 에러

### ISSUE THREAD

**Issue by nozomu03** [humit0/kakao_auto_reply#43]
<Directory /var/www/html/lee>
	       Options +FollowSymLinks +MultiViews +Indexes
	    AllowOverride All
              AddType application/x-httpd-php .php
	    Order allow,deny
	    allow from all
	</Directory>

이걸 통해서 .php를 붙이지 않고도 php파일로 갈 수 있게 했습니다.
그런데도 계속 415 에러가 나더군요
왜 그럴까요?
주소는
http://busan-c.iptime.org/lee/
입니다.

**Comment by humit0** [comment]
message.php나 keyboard.php에서 echo로 결과를 출력하기 전에 header("Content-Type: application/json; charset=utf-8"); 를 추가해주셔야 합니다.
