### ISSUE TITLE
키보드 입력 통신

### ISSUE THREAD

**Issue by ltm-lab** [humit0/kakao_auto_reply#5]
블로그에서 '엘템군'이라는 닉네임으로 질문드렸던 학생입니다!

제가 키보드 입력을 받고 싶다고 했었는데 약간 잘못 말씀드린것 같습니다..

말씀해주신 부분은 키보드 입력을 통해 '버튼을 실행'하는 방법이고 제가 원하는것은 키보드 입력받은것을 이용하여 출력을 하는 방법입니다.

예를들어, '이름입력'이라는 버튼을 눌렀을때 '이름이 뭐야?'라는 메세지를 보내며 키보드를 띄워줍니다. 사용자는 본인의 이름을 입력하여 전송합니다. 그럼 그 메세지의 답으로 '아 너의 이름은 {본인의 이름}이구나? 알겠어!' 이런 기능이 구현하고 싶은거거든요.. 불가능한가요?

**Comment by humit0** [comment]
카카오톡 서버에서 이전 응답에 대한 정보를 주지 않으며, 또한 일정시간이 지나면 이전 응답에 대한 내용을 전부 초기화 시키므로 현재 단계에서는 그러한 기능을 추가하기가 어렵습니다.

물론 응답 로그를 기록하고, 코어 파일을 수정한다면 가능할 수는 있습니다만, 이 기능을 추가할 계획은 아직까지 없습니다.
