### ISSUE TITLE
같은 이름 버튼

### ISSUE THREAD

**Issue by ltm-lab** [humit0/kakao_auto_reply#6]
버튼 이름을 같게해도 작업을 다르게 할 수 있는 방법은 없나요?
예를 들어, 서울 -> 날씨 = 서울날씨 | 경기도 -> 날씨 = 경기도날씨 이런식으로요..
버튼 이름은 '날씨'로 같지만 작업을 다르게 하는..

**Comment by humit0** [comment]
이전의 메시지 로그를 저장하고 있지 않는 이상 구현을 할 수 있는 방법이 없습니다.
기본적으로 카카오톡에서 버튼의 이름으로 메시지를 호출을 하기 때문에 그렇습니다.
