### ISSUE TITLE
자동응답 무반응

### ISSUE THREAD

**Issue by terryeah** [humit0/kakao_auto_reply#7]
http://humit.tistory.com/250
이 블로그 포스트 따라 다 설치하고 키보드 initialization도 잘 맞췄는데 봇에다가 어떤 톡을 보내든 톡 자체를 읽지를 않네요.

첫 키보드에 나오는 버튼에는 잘 반응합니다. 옐로페이지에서 일대일 대화 설정도 평일에는 대화 가능하게 되어있구요. 

어떻게 고쳐야 할까요?

**Comment by humit0** [comment]
톡 자체를 읽지 않는다는 내용이 어떤 내용인지 정확히 설명해주시기 바랍니다.

**Comment by terryeah** [comment]
[Image Link](https://puu.sh/qtXOF/cf69dbf5fc.png)
이렇게 톡을 보냈는데도 봇이 읽지를 않는 현상이 일어납니다. 

resource/msg 폴더에 있는 PHP 파일 중 하나에는 아래와 같은 코드가 들어있구요.

```
<?php
// content : 안녕하세요
use \kakao\Msg;
use \kakao\Msg\Message;
use \kakao\Keyboard;

echo new Msg(
    new Message(
        "네, 안녕하세요. 만나서 반갑습니다!",
        NULL,
        NULL
    ),
    TRUE
);
```

**Comment by humit0** [comment]
지금 사진에서 우측 하단을 보시면 1:1 기능이 켜져 있는 것을 확인할 수 있습니다.
1:1 대화와 봇은 서로 독립적인 기능으로 서로 각자의 응답을 받을 수 있는 방법이 없습니다. 즉 1:1 대화에서는 봇이 읽을 수 있는 방법이 없습니다.

**Comment by terryeah** [comment]
1:1 대화에서는 봇이 유저의 input을 읽을 수 있는 방법이 아예 없나요?

**Comment by humit0** [comment]
네 아예 없습니다
