### ISSUE TITLE
API TEST 실패..

### ISSUE THREAD

**Issue by Cafri** [humit0/kakao_auto_reply#8]
API 테스트 시도시 아래와 같은 에러가 발생합니다.

Initialize Api test : Fail 200 : wrong keyboard initialization

서버는 개인서버( http://kakaobot.reversing.co.kr/ ) 쓰고 있고
apache가 아닌 nginx에서 테스트를 해보고 있습니다.

rewrite 문제인거 같아서 nginx 설정에서 아래와 같이 추가해주니

api test 시도시 405에러가 나는데...

location / {
if (!-e $request_filename){ rewrite ^(.*)$ /index.php/?id=$1 break; 
}
}

어떤쪽이 문제가 될까요?

**Comment by humit0** [comment]
nginx는 사용해보지 않아서 답변을 해드릴 수 없습니다.
로그를 확인해서 rewrite가 잘 되는지를 확인해보시기 바랍니다.
