### ISSUE TITLE
500에러

### ISSUE THREAD

**Issue by jia97** [humit0/kakao_auto_reply#9]
안녕하세요
cafe24계정을 사용하고 있습니다.
다운받아서 config랑 .htaccess파일을 수정하고 
접속했더니 500에러가 뜨는데 혹시 이유를 알 수 있을까요?
http://jia97.cafe24.com/
이쪽이 주소입니다.ㅠㅠ

**Comment by humit0** [comment]
cafe24면 mod_rewrite 모듈 문제는 아닌 것으로 보이네요. 일단 접속을 해보니 lib.php 파일을 수정하신 것으로 보입니다.

**Comment by jia97** [comment]
감사합니다 cafe24 php버전을 5.5로 업그레이드 하니 작동합니다^^ 번거롭게 해드려서 죄송합니다.

**Comment by jia97** [comment]
cafe24 php 버전을 5.5로 업그레이드 했더니 동작합니다^^; 번거롭게 해드려서 죄송합니다 감사합니다
